# Generated by Django 4.0.6 on 2022-08-06 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_book_cover_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookrewiev',
            name='created_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
